sonar.projectKey=juanga121_PruebasDemoFront
sonar.organization=juanga121
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/pruebas-demo-front/lcov.info